//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// *** Warning: Please do not edit as changes will be overwritten. This file is auto generated. ***
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.3717")]

